### ISSUE TITLE
strapi not found

### ISSUE THREAD

**Issue by shubibees** [geeky-biz/strapi-plugin-elasticsearch#6]
[2024-10-08 11:01:43.706] info: File created: C:\Users\ibees\Desktop\strapi\century-ply\elastic-search\elasticsearch-data\indices\T7mfJ9r4T16LzMHHS7eKUg\0\index\_7.fdm
strapi-plugin-elasticsearch : searchController : An error was encountered while re-indexing.
ReferenceError: strapi is not defined
    at getPluginStore (C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@geeky-biz\strapi-plugin-elasticsearch\server\services\configure-indexing.js:4:3)
    at Object.getContentConfig (C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@geeky-biz\strapi-plugin-elasticsearch\server\services\configure-indexing.js:65:25)
    at Object.getCollectionConfig (C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@geeky-biz\strapi-plugin-elasticsearch\server\services\configure-indexing.js:30:38)
    at Object.indexCollection (C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@geeky-biz\strapi-plugin-elasticsearch\server\services\perform-indexing.js:96:73)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.rebuildIndex (C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@geeky-biz\strapi-plugin-elasticsearch\server\services\perform-indexing.js:31:21)
    at async Object.rebuildIndex (C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@geeky-biz\strapi-plugin-elasticsearch\server\controllers\perform-indexing.js:9:16)
    at async returnBodyMiddleware (C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@strapi\strapi\dist\services\server\compose-endpoint.js:42:18)
    at async policiesMiddleware (C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@strapi\strapi\dist\services\server\policy.js:15:5)
    at async C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@strapi\strapi\dist\services\server\compose-endpoint.js:27:12

  ReferenceError: strapi is not defined
      at C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@strapi\strapi\dist\middlewares\errors.js:25:7
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@strapi\strapi\dist\middlewares\logger.js:6:5
      at async session (C:\Users\ibees\Desktop\strapi\century-ply\node_modules\koa-session\index.js:41:7)
      at async middleware (C:\Users\ibees\Desktop\strapi\century-ply\node_modules\@strapi\strapi\dist\services\metrics\middleware.js:20:5)

**Comment by geeky-biz** [comment]
Sorry for the super-late response. Could not reproduce this. Please let me know if you can still reproduce this or need inputs on this.

**Comment by geeky-biz** [comment]
Closing since I haven't heard back on this issue and cannot reproduce it.
